#!/usr/bin/python3
def raise_exception():
    return sum(1, 'z')
